development:
    dialect: mysql
    datasource: playground:@tcp(localhost:3306)/playground?parseTime=true
    dir: ./migrations
    table: migrations

production:
    dialect: mysql
    datasource: <username>:<password>@tcp(<ip_address>:3306)/<database>
    dir: ./migrations
    table: migrations

